
#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdio.h>

#if HAVE_CONFIG_H
#include "config.h"
#endif

#include "biolib.h"

#include "imdefs.h"
#include "imscore-dup.h"

#include "nmerscan.h"

/* This data structure is generated by read_13mer_data(), used by
   nmer_count(), and destroyed by delete_13mer_data(). */
static int *freqs = NULL;
static int wordsize = NMER_SIZE;

/* Set a 13mer binary file name, so that 13mer frequency may be read
   into a static data structure in mscore-dup.c file.  When this is
   set, the frequency is immediately read. */
int
read_13mer_data (const char *fn_13mer_b, const int nmer_size)
{
  wordsize = nmer_size;         /* FIXME: disable this? */
  if (fn_13mer_b == NULL)
    return 1;
  else
    {
      freqs = nmer_read_fb (fn_13mer_b, nmer_size);
      return 0;
    }
}

void
delete_13mer_data ()
{
  xfree (freqs);
}

/* Mean of N-mer count per N-mer window */
float
nmer_count (const char *seq, const int seq_l)
{
  int n_wins = MAX_PROBE_LENGTH, distr[MAX_PROBE_LENGTH];
  float ret;

  if (freqs == NULL)
    {
      fprintf (stderr, "N-mer library is not read in.\n");
      return -1.0;
    }

  nmer_dist_dram (seq, seq_l, freqs, wordsize, &n_wins, &distr[0]);

#ifdef DEBUG
  {
    int i;
    char tmp_debug[NMER_SIZE + 1];

    debug0 (__FILE__, __FUNCTION__, __LINE__, "Count 13mer frequency");
    debug_s ("Sequence", seq);

    tmp_debug[NMER_SIZE] = '\0';
    for (i = 0; i < n_wins; i++)
      {
        strncpy (tmp_debug, seq + i, NMER_SIZE);
        debug_i (tmp_debug, distr[i]);
      }
  }
#endif

  ret = ((1.0 * llsum_of_nmer_count (n_wins, distr)) / n_wins);

  return ret;
}

/*
R => methyl.assay <- read.table("data.analysis.tsv", header=TRUE, sep="\t")
R => methyl.clean <- methyl.assay[methyl.assay[["Intensity.penalty"]]==0,]

R => x1 <- with(methyl.clean, c(ASO1.mean, LSO1.mean))
R => x2 <- with(methyl.clean, c(ASO2.mean, LSO2.mean))

R => summary(x1)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
     7.7    571.1   2129.0   5328.0   5295.0 251600.0 

R => summary(x2)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
   587.9   2758.0   5232.0   9818.0  10410.0 281900.0 
 */

/* This function should discriminate ASO1/LSO1 and ASO2/LSO2.  In
   general, ASO1/LSO1 probes have much lower count.  The function has
   to apply more relaxed stringency to ASO2/LSO2 probes. */
float
nmer_score (const float nmer, const allele_type_t allele_type)
{
  float ret;

  assert (allele_type == ALLELE_C || allele_type == ALLELE_T);
  assert (nmer >= 0.0);

  ret = 0.0;
  if (allele_type == ALLELE_C)
    {
      ret = 2.120 - 0.1445 * log (nmer);
    }

  else if (allele_type == ALLELE_T)
    {
      ret = 2.482 - 0.1729 * log (nmer);
    }

  if (ret > 1.0)
    ret = 1.0;
  else if (ret < 0.0)
    ret = 0.0;

  return ret;
}

/*
  Local Variables:
  c-file-style: "gnu"
  End:
*/
